### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#22]
При тестировании ошибок быть не должно
http://joxi.ru/L21PxnzTg97gGm

Например, не должно быть лишних пустых строк. После кода оставляем только одну строку
https://github.com/kirillstepanchuk/Cat-Energy/blob/297a7c6762cc3c4635ca33b995fd26678fdee170/source/sass/style.scss#L20-L29

**Comment by kirillstepanchuk** [comment]
ошибок нет
