### ISSUE TITLE
Параметры шрифтов

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#23]
Наблюдаются множественные несоответствия макету
http://joxi.ru/gmv4yJvTvW61zA

**Comment by Morfey216** [comment]
Подскажи, какой текст содержится в ссылке???
https://github.com/kirillstepanchuk/Cat-Energy/blob/81f06d680302548bd51afcb5386e2e6f5a44be29/source/catalog.html#L44-L46

а что за стили в таком случае тут прописаны?
https://github.com/kirillstepanchuk/Cat-Energy/blob/81f06d680302548bd51afcb5386e2e6f5a44be29/source/sass/blocks/product.scss#L10-L15

http://joxi.ru/BA0PX30TPDV8EA

**Comment by kirillstepanchuk** [comment]
Испрваил

**Comment by kirillstepanchuk** [comment]
Исправил
