### ISSUE TITLE
Нарушения БЭМ

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#24]
1.
В файле global можно размещать только глобальные настройки.
`.button` и `.page-footer` - у этих стилей есть (должны быть) свои собственные блоки и свои собственные файлы!
https://github.com/kirillstepanchuk/Cat-Energy/blob/297a7c6762cc3c4635ca33b995fd26678fdee170/source/sass/base/global.scss#L6-L18

2.
Здесь, например, вообще полная каша!!!!!!
Файл для одного блока (catalog.scss), а внутри всё что угодно, но только не стили для этого блока!
https://github.com/kirillstepanchuk/Cat-Energy/blob/297a7c6762cc3c4635ca33b995fd26678fdee170/source/sass/blocks/catalog.scss#L1-L25

**Comment by Morfey216** [comment]
не вижу, что исправлены ошибки по БЭМ
https://github.com/kirillstepanchuk/Cat-Energy/blob/81f06d680302548bd51afcb5386e2e6f5a44be29/source/sass/blocks/about-product.scss#L1-L8

**Comment by kirillstepanchuk** [comment]
Исправил

**Comment by Morfey216** [comment]
В модификаторе не нужно заново дублировать основные стили. Вероятно, ты не до конца понял, как применяется БЭМ... Если присутствует модифицированный блок, то к нему применяют ДВА класса: основной и класс-модификатор. Следовательно - основные стили прописаны в основном селекторе, а измененные - в модифицированном.

https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/base/buttons.scss#L24

**Comment by Morfey216** [comment]
> Исправил

нет, не всё :
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/blocks/selection.scss#L5-L8

**Comment by kirillstepanchuk** [comment]
до меня долго доходило про модификатор, но дошло, исправил

**Comment by Morfey216** [comment]
С модификатором кнопки пока еще не закончили )
вот скриншот: http://joxi.ru/1A5P7NxTGXzW12
Здесь хорошо видно, что свойство непрозрачности полностью дублируется...
https://github.com/kirillstepanchuk/Cat-Energy/blob/c1766c607d58c57725752df5daedb36910999c67/source/sass/base/buttons.scss#L28-L30
https://github.com/kirillstepanchuk/Cat-Energy/blob/c1766c607d58c57725752df5daedb36910999c67/source/sass/base/buttons.scss#L36-L38

**Comment by kirillstepanchuk** [comment]
не досмотрел, исправил
