### ISSUE TITLE
Альтернативный шрифт

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#29]
Множественные нарушения!!! 
https://github.com/kirillstepanchuk/Cat-Energy/blob/81f06d680302548bd51afcb5386e2e6f5a44be29/source/sass/blocks/about-product.scss#L6

**Comment by kirillstepanchuk** [comment]
Добавил

**Comment by kirillstepanchuk** [comment]
Добавил веб-безопасный шрифт

**Comment by Morfey216** [comment]
> Добавил веб-безопасный шрифт

Не везде :
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/blocks/selection.scss#L5-L8

**Comment by kirillstepanchuk** [comment]
исправил
