### ISSUE TITLE
Высота блока

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#30]
Ты вроде как давно в курсе, что нужно быть аккуратным с прописыванием в стилях высоты блока (height). Ниже набор параметров:
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/base/buttons.scss#L2
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/base/buttons.scss#L6
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/base/buttons.scss#L12-L13
https://github.com/kirillstepanchuk/Cat-Energy/blob/767c147fb2580713ef35654a1362ae8bb08af014/source/sass/base/buttons.scss#L16

Вот так будут выглядеть кнопки, если указать размер шрифта и высоту линий по 72px. (цвет умышленно изменен на красный для наглядности)
http://joxi.ru/Rmz4JpxTRPY7KA

А должны выглядеть вот так: http://joxi.ru/gmv4yJvTvPqwDA

**Comment by kirillstepanchuk** [comment]
Исправил

**Comment by Morfey216** [comment]
А мне кажется, что проблема осталась:
http://joxi.ru/Drl4Z5oT0wGEdr

**Comment by kirillstepanchuk** [comment]
ну теперь исправил
