### ISSUE TITLE
Нейминг

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#38]
Нужно стараться так подбирать именования, чтобы не допускать двусмысленных толкований.
https://github.com/kirillstepanchuk/Cat-Energy/blob/e1fbb291abe2b8da31381be9faed6a671ba4ea2a/source/index.html#L37

Класс `about-site__text` лучше заменить на `about-site__content`
тогда понятно, что речь идет о наполнении блока, а не просто о тексте

**Comment by kirillstepanchuk** [comment]
Заменил
