### ISSUE TITLE
Контентные изображения

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#39]
http://joxi.ru/LmG1PXeIJ6vdJA
Данное изображение является контентным. Следовательно - это не фон!

https://github.com/kirillstepanchuk/Cat-Energy/blob/e1fbb291abe2b8da31381be9faed6a671ba4ea2a/source/sass/blocks/about-site.scss#L34
https://github.com/kirillstepanchuk/Cat-Energy/blob/e1fbb291abe2b8da31381be9faed6a671ba4ea2a/source/sass/blocks/about-site.scss#L119

**Comment by kirillstepanchuk** [comment]
Переделал
