### ISSUE TITLE
Декоративные изображения

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#41]
Интересно, что натолкнуло тебя на "светлую" мысль поместить поместить декоративное изображение в разметку?
https://github.com/kirillstepanchuk/Cat-Energy/blob/e1fbb291abe2b8da31381be9faed6a671ba4ea2a/source/catalog.html#L315-L317

**Comment by kirillstepanchuk** [comment]
Убрал
