### ISSUE TITLE
Избыточный параграф

### ISSUE THREAD

**Issue by Morfey216** [kirillstepanchuk/Cat-Energy#44]
Нарушение критерия Д2
https://github.com/kirillstepanchuk/Cat-Energy/blob/e1fbb291abe2b8da31381be9faed6a671ba4ea2a/source/catalog.html#L326-L329

В данном месте второй параграф не нужен, как и обертка вокруг параграфов. Вопрос можно решить элегантнее
`<p class="adress__place">ул. Большая Конюшенная, д. 19/8 <span>Санкт-Петербург</span></p>`

**Comment by kirillstepanchuk** [comment]
Заменил
